sudo: requied
services:
  - docker

before_install:
  - docker build -t dquez/client-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run dquez/client-test npm test -- --coverage

after_success:
  - docker build -t dquez/streamezy-client ./client
  - docker build -t dquez/streamezy-nginx ./nginx
  - docker build -t dquez/streamezy-server ./server
  - docker build -t dquez/streamezy-rtmpserver ./rtmpserver
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dquez/streamezy-client
  - docker push dquez/streamezy-nginx
  - docker push dquez/streamezy-server
  - docker push dquez/streamezy-rtmpserver