sudo: requied
services:
  - docker

before_install:
  - docker build -t dquez/client-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run dquez/client-test npm test -- --coverage

after_success:
  - docker build -t dquez/streamezy-client ./client
  - docker build -t dquez/streamezy-nginx ./nginx
  - docker build -t dquez/streamezy-server ./server
  - docker build -t dquez/streamezy-rtmpserver ./rtmpserver
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dquez/streamezy-client
  - docker push dquez/streamezy-nginx
  - docker push dquez/streamezy-server
  - docker push dquez/streamezy-rtmpserver

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: streamezy
  env: Streamezy-env
  bucket_name: elasticbeanstalk-us-east-1-172287926365
  bucket_path: streamezy
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

    
