version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
      - "45011:45011"
  server:
    image: dquez/streamezy-server
    env_file:
      - .env 
  client:
    image: dquez/streamezy-client
  rtmp:
    build:
      dockerfile: Dockerfile
      context: ./rtmpserver
    ports:
      - '1935:1935'
      - '8000:8000'
        