version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
      - '8000:81'
      # - '1935:1935'
  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
      - "45011:45011"
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app 
    env_file:
      - ./server/.env 
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  rtmp:
    build:
      dockerfile: Dockerfile
      context: ./rtmpserver
    ports:
      - '8000:80'
      - '1935:1935'  