version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app 
    env_file:
      - .env 
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  rtmp:
    build:
      dockerfile: Dockerfile
      context: ./rtmpserver
    ports:
      - '1935:1935'
      - '8000:8000'
        